/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:869455f5-0b25-4304-b282-56db77b46f6b",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_WgsPz9JY7",
    "aws_user_pools_web_client_id": "7e8o8l2s9s6ide85bvhrakk9p5",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://outfj5olvrd3dggdyv7uzhszxq.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-er2t5rmsqndktedobehigqpjdm",
    "aws_user_files_s3_bucket": "amplifyappb50a6fd7b73c48e2804a605e5879997a174151-staging",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
